// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using j2p.Infra.Data.Context;

namespace j2p.Infra.Data.Migrations
{
    [DbContext(typeof(j2pContext))]
    [Migration("20190627005940_Setup")]
    partial class Setup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("j2p.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(36);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Player");
                });

            modelBuilder.Entity("j2p.Domain.Entities.Player", b =>
                {
                    b.OwnsOne("j2p.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("PlayerId");

                            b1.Property<string>("Adress")
                                .IsRequired()
                                .HasColumnName("Email")
                                .HasMaxLength(200);

                            b1.HasKey("PlayerId");

                            b1.ToTable("Player");

                            b1.HasOne("j2p.Domain.Entities.Player")
                                .WithOne("Email")
                                .HasForeignKey("j2p.Domain.ValueObjects.Email", "PlayerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("j2p.Domain.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("PlayerId");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnName("FirstName")
                                .HasMaxLength(50);

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnName("LastName")
                                .HasMaxLength(50);

                            b1.HasKey("PlayerId");

                            b1.ToTable("Player");

                            b1.HasOne("j2p.Domain.Entities.Player")
                                .WithOne("Name")
                                .HasForeignKey("j2p.Domain.ValueObjects.Name", "PlayerId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
